// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PasswordHashService is an autogenerated mock type for the PasswordHashService type
type PasswordHashService struct {
	mock.Mock
}

// HashPassword provides a mock function with given fields: ctx, plain
func (_m *PasswordHashService) HashPassword(ctx context.Context, plain string) (string, error) {
	ret := _m.Called(ctx, plain)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, plain)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, plain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
